### ISSUE TITLE
Charts[Network Node]: Refactor Values file definitions

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#159]
### Example Refactor for Sidecar Properties and Enabled Flag

```
    sidecars:
        recordStreamUploader:
          enabled: true
          nameOverride: ""
          image:
            pullPolicy: IfNotPresent
            registry: gcr.io
            repository: mirrornode/hedera-mirror-importer
            tag: ""  # Defaults to the chart's app version
          config:
            watchDir: /opt/hgcapp/recordstream  # should not be configurable
            csvStatsDir: /opt/hgcapp/recordstream/uploader-stats/  # should not be configurable
            bucketPath: /recordstream   # should not be configurable
            bucketName: "dev" # extract to top-level configuration (1 for backups and 1 for streams shared across all node)
            compression: true
            sidecar: true
```
