### ISSUE TITLE
Charts[Network Node]: Ensure CI pipeline tests network node installation

### ISSUE THREAD

**Issue by nathanklick** [hashgraph/full-stack-testing#202]
## User Story

**As a _software engineer_**, 

**I want**
> the CI pipeline, for both manual and PR based triggered runs, to perform all available Helm chart tests.

**So that**
> I can be assured my changes did not break the Helm chart.
 
## Assumptions

- The `helm test` command runs all available tests.

## Requested Changes

- Add the following workflow level permissions near the top of the `zxc-compile-code.yaml` CI workflow:
   ```
    permissions:
         id-token: write
         contents: read
   ```
- Add the following GCP authentication steps to the `zxc-compile-code.yaml` CI workflow:
  ```
      - name: Authenticate to Google Cloud
        id: google-auth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d # pin@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: "projects/101730247931/locations/global/workloadIdentityPools/hedera-registry-pool/providers/hedera-registry-gh-actions"
          service_account: "swirlds-automation@hedera-registry.iam.gserviceaccount.com"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@d51b5346f85640ec2aa2fa057354d2b82c2fcbce # pin@v1
  ```
- Update the Makefile to add the `setup-nodes` and `start-nodes` targets as prerequisite for the `test` target.
- Update the CI pipeline to run both NMT and Direct install variants:
   - `make test SCRIPT_NAME=direct-install.sh`
   - `make test SCRIPT_NAME=nmt-install.sh`
