### ISSUE TITLE
Charts[GKE-BUG] Apply nodeSelector to all pods in the chart including proxies

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/full-stack-testing#373]
Currently network-node pods are scheduled based on the following settings:
```
  nodeSelectors:
    fullstack-scheduling.io/os: linux
    fullstack-scheduling.io/role: network
  tolerations:
    - key: "fullstack-scheduling.io/os"
      operator: "Equal"
      value: "linux"
      effect: "NoSchedule"
    - key: "fullstack-scheduling.io/role"
      operator: "Equal"
      value: "network"
      effect: "NoSchedule"
```

We need to ensure these settings are applied for all pods in the chart including proxies.
