### ISSUE TITLE
Charts[Network]: helm install fails with fst chart version in solo

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/full-stack-testing#871]
with v0.26.0 of Solo (actually linked at commit: 37d44f304510d29e8424683814960c707a7fa142)

```
#!/bin/bash
readonly KIND_IMAGE="kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72"
export SOLO_NAMESPACE=solo-large
export SOLO_CLUSTER_SETUP_NAMESPACE=fullstack-setup
solo init --namespace "${SOLO_NAMESPACE}" -i node0,node1,node2,node3,node4,node5,node6 -t v0.50.0 -s "${SOLO_CLUSTER_SETUP_NAMESPACE}" || exit 1
solo cluster setup  || exit 1
```

```
#!/bin/bash
export SOLO_NAMESPACE=solo-large
export SOLO_CLUSTER_SETUP_NAMESPACE=fullstack-setup
solo init --namespace "${SOLO_NAMESPACE}" -i node0,node1,node2,node3,node4,node5,node6 -t v0.50.0 -s "${SOLO_CLUSTER_SETUP_NAMESPACE}" || exit 1
solo node keys --gossip-keys --tls-keys --key-format pem || exit 1
solo network deploy --values-file /Users/user/Downloads/init-containers-values.yaml --profile large --fst-chart-version 0.27.0 || exit 1
solo node setup || exit 1
solo node start || exit 1
```

```
❯ helm install fullstack-deployment full-stack-testing/fullstack-deployment --version 0.27.0 -n solo-large --create-namespace  --values /Users/user/Downloads/init-containers-values.yaml --values /Users/user/.solo/cache/values-files/fst-large.yaml --set "hedera-mirror-node.enabled=false" --set "hedera-explorer.enabled=false" --set "telemetry.prometheus.svcMonitor.enabled=false" --set "defaults.root.image.repository=hashgraph/full-stack-testing/ubi8-init-java21" --dry-run>x.txt
Error: INSTALLATION FAILED: template: fullstack-deployment/templates/network-node-statefulset.yaml:168:18: executing "fullstack-deployment/templates/network-node-statefulset.yaml" at <include "fullstack.container.image" (dict "image" $root.image "Chart" $.Chart "defaults" $root)>: error calling include: template: fullstack-deployment/templates/_helpers.tpl:43:49: executing "fullstack.container.image" at <.defaults.image.registry>: nil pointer evaluating interface {}.registry
 ```

fix:
in `_helpers.tpl`
need to change all instances of `.defaults.image` to `.defaults.root.image`

root cause:
```
❯ cat /Users/user/.solo/cache/values-files/fst-large.yaml
hedera:
  nodes:
    - name: node0
      accountId: 0.0.3
      root:
        resources:
          requests:
            cpu: 18000m
            memory: 32000Mi
          limits:
            cpu: 24000m
            memory: 64000Mi
...
```
