### ISSUE TITLE
Charts[Network]: move mkdir and chmod from startup probe to init container

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/full-stack-testing#972]
[The following code](https://github.com/hashgraph/full-stack-testing/blob/889bf67f42d88fd6cf0467b72344123425667c8d/charts/fullstack-deployment/templates/network-node-statefulset.yaml#L150) for the root container is not guaranteed to execute first, instead it should be moved to the initContainer:
```
      # Root Container: {{ $node.name }}-root-container
      - name: {{ $root.nameOverride | default "root-container" }}
        startupProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - |
                task() {
                  mkdir -p /opt/hgcapp/recordStreams/record{{ $node.accountId }}/sidecar
                  chmod 777 /opt/hgcapp/recordStreams/record{{ $node.accountId }}/sidecar
                }
                task
```

- [ ] remove the startupProbe from the root container in `charts/fullstack-deployment/templates/network-node-statefulset.yaml`
- [ ] add the volumeMounts to the initContainer:
```
        volumeMounts:
          - name: hgcapp-record-streams
            mountPath: /opt/hgcapp/recordStreams
            subPath: record{{ $node.accountId }}
```
- [ ] add the mkdir and chmod commands into the initContainer command
